name: filesystem-reader
base: core22
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: reader of all files
description: |
  this is just something I've thrown together to test the system-backup interface

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  fs-reader:
    plugin: dump
    source: src/
    organize:
        reader.sh: bin/reader.sh

apps:
  fs-reader:
    command: bin/reader.sh
    plugs: [ system-backup ]

 
